// Regenerates extension/psl-data.js from the Public Suffix List.
//
//   node tools/generate-psl.mjs [path-to-public_suffix_list.dat]
//
// With no argument the current list is downloaded from publicsuffix.org. The
// generated file is committed so the extension never performs a network lookup
// at runtime; this script exists so the data stays reproducible and reviewable.
//
// Single-label rules such as "com" are dropped. A single-label public suffix
// yields a registrable domain of the last two labels, which is exactly what the
// parser already falls back to, so keeping them would add weight without
// changing any decision.

import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUTPUT = fileURLToPath(new URL("../extension/psl-data.js", import.meta.url));

async function readList(argument) {
  if (argument) {
    return { text: readFileSync(argument, "utf8"), origin: argument };
  }

  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Unable to download the list: ${response.status}`);
  }
  return { text: await response.text(), origin: SOURCE_URL };
}

function parseRules(text) {
  const icann = [];
  const priv = [];
  let section = "icann";

  for (const line of text.split("\n")) {
    const trimmed = line.trim();

    if (trimmed.startsWith("// ===BEGIN PRIVATE")) {
      section = "private";
      continue;
    }
    if (trimmed.startsWith("// ===BEGIN ICANN")) {
      section = "icann";
      continue;
    }
    if (!trimmed || trimmed.startsWith("//")) {
      continue;
    }

    const labels = trimmed.replace(/^!/, "").split(".");
    const isSignificant =
      labels.length > 1 || trimmed.startsWith("!") || trimmed.includes("*");

    if (isSignificant) {
      (section === "private" ? priv : icann).push(trimmed);
    }
  }

  return {
    icann: [...new Set(icann)].sort(),
    private: [...new Set(priv)].sort()
  };
}

function toTable(rules) {
  // Leading and trailing separators so a lookup is an exact "\n<rule>\n"
  // containment test rather than an accidental substring match.
  return `\n${rules.join("\n")}\n`;
}

const { text, origin } = await readList(process.argv[2]);
const rules = parseRules(text);
const total = rules.icann.length + rules.private.length;

if (rules.icann.length < 3000 || rules.private.length < 1000) {
  throw new Error(
    `Parsed ${rules.icann.length} ICANN and ${rules.private.length} private rules; the source looks wrong.`
  );
}

const file = `// Generated by tools/generate-psl.mjs. Do not edit by hand.
//
// Source: ${SOURCE_URL}
// Retrieved: ${new Date().toISOString().slice(0, 10)}
// Rules: ${total} multi-label, wildcard, and exception rules
// (${rules.icann.length} ICANN, ${rules.private.length} private). Single-label rules are
// omitted because they match the parser's default behavior of taking the last
// two labels.
//
// The two sections are kept apart because they answer different questions. Both
// together give the registrable domain. The private section alone identifies a
// multi-tenant hosting boundary, where separate tenants are separate sites but
// the provider label is not evidence of brand impersonation.
//
// Each table is one newline-delimited string rather than a Set or an array, so
// it costs a single string per content-script context instead of thousands of
// small ones. Lookups are exact "\\n<rule>\\n" containment tests. See
// getRegistrableDomain in content.js.

const ICANN_SUFFIX_RULES = ${JSON.stringify(toTable(rules.icann))};

const PRIVATE_SUFFIX_RULES = ${JSON.stringify(toTable(rules.private))};
`;

writeFileSync(OUTPUT, file);
console.log(
  `Wrote ${total} rules (${rules.icann.length} ICANN, ${rules.private.length} private) from ${origin} to ${OUTPUT}`
);
